events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {
    listen 3001;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
      proxy_pass http://orchestrator-api:8001;
      proxy_set_header Host $host;
    }

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
