"use client";
import { useEffect, useState } from "react";
import { gatewayFetch } from "@foxbrain/api-client";
import { AICard, CustomerCard, DecisionCard, InsightCard } from "@foxbrain/ui";
export default function HuyanPage() {
  const [status, setStatus] = useState("同步经营信号中");
  useEffect(() => { gatewayFetch("/api/ceo/dashboard").then(response => setStatus(response.ok ? "已同步 · 09:30" : "使用上次已验证快照")).catch(() => setStatus("使用上次已验证快照")); }, []);
  return <main className="app-shell huyan"><header className="topbar"><a className="brand" href="#top">VAFOX <span>虎眼</span></a><nav aria-label="CEO 智能中心"><a className="active" href="#today">TODAY</a><a href="#signals">经营信号</a><a href="#decisions">决策事项</a></nav><span className="live-dot">{status}</span></header><section id="top" className="hero ceo-hero"><div><p className="eyebrow">CEO AI INTELLIGENCE CENTER</p><h1>VAFOX<br /><em>TODAY</em></h1><p className="lead">把分散的经营事实，转化为今天可被确认的决策。</p></div><div className="hero-metric"><span>本周销售达成</span><strong>78.4%</strong><p>较上周同期 <b>+8.2%</b></p></div></section><section id="signals" className="insight-grid"><InsightCard metric="销售摘要 · ¥2.84M" risk="周末目标仍有 ¥0.79M 缺口" opportunity="南山与航苑店贡献了 61% 增量" source="Retail Brain · 09:30" /><InsightCard metric="库存风险 · 3 个信号" risk="M 尺码外壳在 2 家门店低于安全线" opportunity="跨店调拨可覆盖 72% 需求" source="Product Intelligence · 09:20" /><CustomerCard customer="客户机会 · 42 人" profile="高意向户外客户，本周有浏览或到店行为" equipment="拥有核心装备，缺少防水层或保暖层" opportunity="预计可转化销售 ¥96,000" /></section><section className="section-heading"><div><p className="eyebrow">EXECUTIVE RECOMMENDATION</p><h2>一个需要关注的经营动作</h2></div><span className="confidence">高置信度</span></section><section className="executive-grid"><AICard question="将南山店作为周末轻徒步活动主阵地" analysis="天气、库存结构及高意向客群在同一时间窗口出现。" recommendation="批准跨店调拨，并授权活动名单触达。" citation="Runtime · Retail · Customer" confidence="置信度 91%" /><DecisionCard problem="周末轻徒步活动资源配置" options="批准南山活动 / 保持现有排班" impact="预计新增 ¥48,000–¥72,000 销售机会" approval="等待 CEO 审批" /></section></main>;
}
